services:
  app:
    image: docker-spring-boot-postgres:latest
    build:
      context: .
    container_name: app
    ports:
      - "6868:8080"
    networks:
      - my-network-name
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_ranti
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    networks:
      - my-network-name
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_ranti
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/import.sql:/docker-entrypoint-initdb.d/import.sql

volumes:
  db_data:

networks:
  my-network-name:
    name: springcloud
